--RBAC

-- 1. Tạo các Roles ứng với các quyền .
USE #HeThongNhaSach
CREATE ROLE BPDH;
CREATE ROLE NVQL;
CREATE ROLE QLNH;
CREATE ROLE QLNS;
CREATE ROLE NVBH;
CREATE ROLE KTBH;
GO

-- 2. Cấp quyền cho các Roles dựa vào ma trận quyền truy xuất.
-- Role Bộ phận điều hành
GRANT SELECT			 ON CHUCVU		TO BPDH;
GRANT SELECT 			 ON NHANVIEN	TO BPDH;
GRANT SELECT			 ON NHAXUATBAN	TO BPDH;
GRANT SELECT 			 ON SACH		TO BPDH;
GRANT SELECT			 ON HOADON		TO BPDH;
GRANT SELECT			 ON CHITIETHD	TO BPDH;
GRANT SELECT 			 ON PHANPHOISACH	TO BPDH;
GRANT SELECT			 ON NHASACH		TO BPDH;
GRANT SELECT			 ON LOAISACH	TO BPDH;
GO

-- 3. Tạo đăng nhập cho các người dùng có trong bảng NHANVIEN với mật khẩu tùy ý.
CREATE LOGIN BPDH_1 WITH PASSWORD = '40bd001563085fc35165329ea1ff5c5ecbdbbeef';
CREATE USER NV01 FOR LOGIN BPDH_1;
ALTER ROLE BPDH ADD MEMBER NV01;


USE #HeThongNhaSach
GO

-- Role Nhân viên Quản lý
GRANT SELECT, INSERT, UPDATE 	ON dbo.LOAISACH 			TO NVQL;
GRANT SELECT, INSERT, UPDATE 	ON dbo.NHAXUATBAN			TO NVQL;
GRANT SELECT , INSERT, UPDATE	ON dbo.NHASACH				TO NVQL;
GRANT SELECT , INSERT, UPDATE	ON dbo.SACH					TO NVQL;
GRANT SELECT , INSERT, UPDATE	ON dbo.PHANPHOISACH			TO NVQL;
GRANT SELECT ON dbo.NHANVIEN			TO NVQL;
GO

CREATE LOGIN NVQL_1 WITH PASSWORD = '40bd001563085fc35165329ea1ff5c5ecbdbbeef';
CREATE USER NV02 FOR LOGIN NVQL_1;
ALTER ROLE NVQL ADD MEMBER NV02;


--
-- Role Quản lý nhập hàng
GRANT SELECT 						 ON SACH				TO QLNH;
GRANT SELECT 						 ON dbo.LOAISACH		TO QLNH;
GRANT SELECT 						 ON dbo.NHAXUATBAN		TO QLNH;
GRANT SELECT 						 ON dbo.NHANVIEN		TO QLNH;
GRANT SELECT , INSERT, UPDATE		 ON HOADON		TO QLNH;
GRANT SELECT, INSERT, UPDATE		 ON CHITIETHD	TO QLNH;
GO

CREATE LOGIN QLNH_1 WITH PASSWORD = '40bd001563085fc35165329ea1ff5c5ecbdbbeef';
CREATE USER NV03 FOR LOGIN QLNH_1;
ALTER ROLE QLNH ADD MEMBER NV03;

-- Role Quản lý nhân sự
GRANT SELECT							 ON CHUCVU		TO QLNS;
GRANT SELECT, INSERT, UPDATE 			 ON NHANVIEN	TO QLNS;
GO

CREATE LOGIN QLNS_1 WITH PASSWORD = '40bd001563085fc35165329ea1ff5c5ecbdbbeef';
CREATE USER NV04 FOR LOGIN QLNS_1;
ALTER ROLE QLNS ADD MEMBER NV04;

-- Role Nhân viên bán hàng
GRANT SELECT 							 ON NHANVIEN	TO NVBH;
GRANT SELECT 							 ON SACH		TO NVBH;
GRANT SELECT, INSERT, UPDATE			 ON HOADON		TO NVBH;
GRANT SELECT, INSERT, UPDATE			 ON CHITIETHD	TO NVBH;
GO

-- 3. Tạo đăng nhập cho các người dùng có trong bảng NHANVIEN với mật khẩu tùy ý.
CREATE LOGIN NVBH_1 WITH PASSWORD = '40bd001563085fc35165329ea1ff5c5ecbdbbeef';
CREATE USER NV05 FOR LOGIN NVBH_1;
ALTER ROLE NVBH ADD MEMBER NV05;